extraction:
  java:
    index:
      java_version: 11
      gradle:
        version: 6.8.1
      
path_classifiers:
  docs:
    - "LICENSE*"
    - "*.md"
    - "*.html"
  ci:
    - "appveyor.yml"
    - ".codecov.yml"
    - ".travis.yml"
    - ".circleci"
    - ".dependabot"
    - ".github"
    - ".lgtm.yml"
